title: Insights Network
email: hello@insights.network
description: > # this means to ignore newlines until "baseurl:"
  Insights Network is a new era of data collection
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: insightsnetwork
github_username:  InsightsNetwork

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed
sass:
  sass_dir: _sass
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
